config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :restaurants do
  # resources :reviews, only: [:new, :create]
  # end
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
  # # get "restaurants", to: "restaurants#index"
  # get "restaurants/new", to:  "restaurants#new"
  # post "restaurants", to: "restaurants#create"
  # get "restaurants/:id", to: "restaurants#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true

  validates :category, inclusion: { in: %w(chinese italian japanese french belgian) }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true

  validates :rating, inclusion: { in: 0..5 }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurants_path
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    restaurant.update(restaurant_params)

    # no need for app/views/restaurants/update.html.erb
    redirect_to restaurants_path
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_num, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    # we need @restaurant in our `simple_form_for`
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    # we need `restaurant_id` to associate review with corresponding restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= restaurant.name %> - <%= restaurant.address %> - <%= restaurant.phone_number %> - <%= restaurant.category %></li>
    <%= link_to 'Voir', restaurant_path(restaurant) %>
  <% end %>
</ul>

<%= link_to 'Add a restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= simple_form_for [ @restaurant ] do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit "Submit restaurant", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone_number %></p>
<p><%= @restaurant.category %></p>

<%= link_to 'Add a new review', new_restaurant_review_path(@restaurant) %>

<ul>
  <% @restaurant.reviews.each do |review| %>
    <li><%=review.content%> - <%=review.rating%></li>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :rating %>
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>

<%= link_to 'Back to restaurant', restaurant_path(@restaurant) %>
<% end %>